---
openapi: 3.0.1
info:
  title: API - 이룸오더
  description: API Description
  version: v1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Order Management
    description: API for managing orders
paths:
  "/orders":
    post:
      tags:
        - Order Management
      summary: Create Order
      description: Creates a new order based on provided details.
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/OrderRequestDto"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/OrderResponseDto"
components:
  schemas:
    LocalTime:
      type: object
      properties:
        hour:
          type: integer
          format: int32
        minute:
          type: integer
          format: int32
        second:
          type: integer
          format: int32
        nano:
          type: integer
          format: int32
      example: '01:20'
    MenuDetailDto:
      type: object
      properties:
        useCup:
          type: string
          example: TakeOut
        addShot:
          type: boolean
        addVanilla:
          type: boolean
        addHazelnut:
          type: boolean
        light:
          type: boolean
    OrderMenuDto:
      type: object
      properties:
        menuId:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
        menuOptions:
          "$ref": "#/components/schemas/MenuDetailDto"
    OrderRequestDto:
      type: object
      properties:
        userId:
          type: integer
          format: int32
        totalPrice:
          type: integer
          format: int32
        pickUp:
          "$ref": "#/components/schemas/LocalTime"
        orderMenuOptions:
          type: array
          items:
            "$ref": "#/components/schemas/OrderMenuDto"
    OrderResponseDto:
      type: object
      properties:
        orderId:
          type: integer
          format: int32
        userId:
          type: integer
          format: int32
        totalPrice:
          type: integer
          format: int32
        orderStatus:
          type: string
          enum:
            - NEW_ORDER
            - WAITING
            - ACCEPTED_ORDER
            - READY_FOR_PICKUP
            - COMPLETED
            - ACCEPTED
            - COOKING_START
            - COOKING_END
            - PICKUP_END
        pickUp:
          "$ref": "#/components/schemas/LocalTime"
        payment:
          type: string
          format: date-time
        orderMenuOptions:
          type: array
          items:
            "$ref": "#/components/schemas/OrderMenuDto"
