---
openapi: 3.0.1
info:
  title: API - 이룸오더
  description: API Description
  version: v1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  "/auth/verifyEmail":
    post:
      tags:
        - auth-controller
      operationId: verifyEmail
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
        - name: code
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: string
  "/auth/signUp":
    post:
      tags:
        - auth-controller
      operationId: signUp
      parameters:
        - name: signUpRequest
          in: query
          required: true
          schema:
            "$ref": "#/components/schemas/SignUpRequest"
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: string
  "/auth/sendEmailVerification":
    post:
      tags:
        - auth-controller
      operationId: sendEmailVerification
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: string
  "/auth/login":
    post:
      tags:
        - auth-controller
      operationId: login
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
        - name: password
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: string
  "/auth/checkId":
    post:
      tags:
        - auth-controller
      operationId: checkId
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: string
  "/api/fcm/register-token":
    post:
      tags:
        - fcm-controller
      operationId: registerToken
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TokenRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: string
components:
  schemas:
    SignUpRequest:
      type: object
      properties:
        id:
          type: string
        password:
          type: string
        email:
          type: string
    TokenRequest:
      type: object
      properties:
        fcmToken:
          type: string
        id:
          type: string
