{
  "openapi": "3.0.1",
  "info": {
    "title": "API - 이룸오더",
    "description": "API Description",
    "version": "v1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/api/sales": {
      "get": {
        "tags": [
          "sales-controller"
        ],
        "summary": "Get Yesterday's Sales",
        "description": "Fetches the total sales data for a specific date and user ID.",
        "operationId": "getYesterdaySales",
        "parameters": [
          {
            "name": "date",
            "in": "query",
            "description": "The date for which to fetch sales data (yyyy-MM-dd)",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date"
            },
            "example": "2023-11-30"
          },
          {
            "name": "userId",
            "in": "query",
            "description": "The user ID requesting the data",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "example": 12345
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved sales data",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/SalesResponse"
                }
              }
            }
          },
          "400": {
            "description": "Invalid input parameters",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/SalesResponse"
                }
              }
            }
          },
          "403": {
            "description": "User not authorized to access this data",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/SalesResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/SalesResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "SalesResponse": {
        "type": "object",
        "properties": {
          "totalSales": {
            "type": "integer",
            "format": "int32"
          }
        }
      }
    }
  }
}