{
  "openapi": "3.0.1",
  "info": {
    "title": "API - 이룸오더",
    "description": "API Description",
    "version": "v1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/api/users/{userId}/routines/{routineId}": {
      "put": {
        "tags": [
          "routine-controller"
        ],
        "summary": "Update an existing routine",
        "description": "Updates the details of an existing routine by routine ID.",
        "operationId": "updateRoutine",
        "parameters": [
          {
            "name": "routineId",
            "in": "path",
            "description": "ID of the routine to be updated",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "example": 1
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RoutineDto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Routine successfully updated",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/RoutineResponseDto"
                }
              }
            }
          },
          "404": {
            "description": "Routine not found",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/RoutineResponseDto"
                }
              }
            }
          },
          "400": {
            "description": "Invalid input",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/RoutineResponseDto"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "routine-controller"
        ],
        "summary": "Delete a routine",
        "description": "Deletes a routine by its ID for a specific user.",
        "operationId": "deleteRoutine",
        "parameters": [
          {
            "name": "routineId",
            "in": "path",
            "description": "ID of the routine to be deleted",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "example": 1
          },
          {
            "name": "userId",
            "in": "path",
            "description": "ID of the user who owns the routine",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "example": 123
          }
        ],
        "responses": {
          "204": {
            "description": "Routine successfully deleted"
          },
          "404": {
            "description": "Routine not found"
          },
          "403": {
            "description": "User not authorized to delete this routine"
          }
        }
      }
    },
    "/api/users/{userId}/routines/add": {
      "post": {
        "tags": [
          "routine-controller"
        ],
        "summary": "Create a new routine",
        "description": "Adds a new routine for the user.",
        "operationId": "createRoutine",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RoutineDto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Routine successfully created",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/RoutineResponseDto"
                }
              }
            }
          },
          "400": {
            "description": "Invalid input",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/RoutineResponseDto"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{userId}/routines": {
      "get": {
        "tags": [
          "routine-controller"
        ],
        "summary": "Get all routines by user ID",
        "description": "Fetches all routines associated with a specific user ID.",
        "operationId": "getAllRoutinesByUserId",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "ID of the user whose routines are to be fetched, long",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "example": 123
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully fetched routines",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/RoutineResponseDto"
                  }
                }
              }
            }
          },
          "404": {
            "description": "User or routines not found",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/RoutineResponseDto"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "LocalTime": {
        "type": "object",
        "properties": {
          "hour": {
            "type": "integer",
            "format": "int32"
          },
          "minute": {
            "type": "integer",
            "format": "int32"
          },
          "second": {
            "type": "integer",
            "format": "int32"
          },
          "nano": {
            "type": "integer",
            "format": "int32"
          }
        },
        "description": "루틴이 실행될 시간",
        "example": "09:00"
      },
      "RoutineDto": {
        "required": [
          "isActivated",
          "menuId",
          "routineDay",
          "routineTime",
          "userId"
        ],
        "type": "object",
        "properties": {
          "userId": {
            "type": "integer",
            "description": "사용자 ID, long",
            "format": "int64",
            "example": 12345
          },
          "menuId": {
            "type": "integer",
            "description": "메뉴 ID",
            "format": "int32",
            "example": 10
          },
          "menuDetailId": {
            "type": "integer",
            "description": "메뉴 세부 정보 ID",
            "format": "int32",
            "example": 5
          },
          "routineDay": {
            "type": "string",
            "description": "루틴이 실행될 요일",
            "example": "MONDAY",
            "enum": [
              "Mon",
              "Tue",
              "Wed",
              "Thu",
              "Fri",
              "Sat",
              "Sun"
            ]
          },
          "routineTime": {
            "$ref": "#/components/schemas/LocalTime"
          },
          "isActivated": {
            "type": "boolean",
            "description": "알람 활성화 여부",
            "example": true
          }
        },
        "description": "Details of the routine to be created"
      },
      "RoutineResponseDto": {
        "type": "object",
        "properties": {
          "routineId": {
            "type": "integer",
            "description": "루틴 ID",
            "format": "int32",
            "example": 1
          },
          "userId": {
            "type": "integer",
            "description": "사용자 ID",
            "format": "int64",
            "example": 12345
          },
          "menuId": {
            "type": "integer",
            "description": "메뉴 ID",
            "format": "int32",
            "example": 10
          },
          "menuDetailId": {
            "type": "integer",
            "description": "메뉴 세부 정보 ID",
            "format": "int32",
            "example": 5
          },
          "routineDay": {
            "type": "string",
            "description": "루틴이 실행될 요일",
            "example": "MONDAY",
            "enum": [
              "Mon",
              "Tue",
              "Wed",
              "Thu",
              "Fri",
              "Sat",
              "Sun"
            ]
          },
          "routineTime": {
            "$ref": "#/components/schemas/LocalTime"
          },
          "activated": {
            "type": "boolean"
          }
        }
      }
    }
  }
}